MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no

OLED_ENABLE = no
#OLED_DRIVER = SSD1306
WPM_ENABLE = no
EXTRAKEY_ENABLE = no       # Audio control and System control
ENCODER_ENABLE = no

#OPT_DEFS += -DHAL_USE_I2C=TRUE