MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
#RGBLIGHT_ENABLE = no
#MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
#COMMAND_ENABLE = yes
#BOOTMAGIC_ENABLE = yes
#NKRO_ENABLE = yes           # Enable N-Key Rollover

RGBLIGHT_ENABLE = no
#WS2812_DRIVER = vendor
#SLEEP_LED_ENABLE = no

OLED_ENABLE = yes
#OLED_DRIVER = SSD1306
WPM_ENABLE = yes
#EXTRAKEY_ENABLE = yes       # Audio control and System control

#ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = yes

OPT_DEFS += -DHAL_USE_I2C=TRUE