MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
#COMMAND_ENABLE = yes
BOOTMAGIC_ENABLE = yes
OLED_ENABLE = no
#OLED_DRIVER = SSD1306
WPM_ENABLE = no
EXTRAKEY_ENABLE = yes       # Audio control and System control
NKRO_ENABLE = yes           # Enable N-Key Rollover
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

RGBLIGHT_ENABLE = no
WS2812_DRIVER = vendor
SLEEP_LED_ENABLE = no

#OPT_DEFS += -DHAL_USE_I2C=TRUE