# Board, Bootloader and MCU
MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
MOUSEKEY_ENABLE = yes
#CONSOLE_ENABLE = yes
#COMMAND_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
SLEEP_LED_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes
EXTRAKEY_ENABLE = yes       # Audio control and System control

OPT_DEFS += -DHAL_USE_I2C=TRUE