// USE PINS 16 AND 17 TO USE 4 PIN JST, IF AVAILABLE
#ifdef ENCODER_ENABLE
#define ENCODERS_PAD_A { GP27 }
#define ENCODERS_PAD_B { GP28 }
#define ENCODER_RESOLUTIONS { 2 }
#define ENCODERS_PAD_A_RIGHT { GP27 }
#define ENCODERS_PAD_B_RIGHT { GP28 }
#define ENCODER_RESOLUTIONS_RIGHT { 2 }
#endif