MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
#MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
SLEEP_LED_ENABLE = yes