MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor
#POINTING_DEVICE_DRIVER = adns9800
#RGBLIGHT_ENABLE = no
#MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
##COMMAND_ENABLE = yes
#BOOTMAGIC_ENABLE = yes
#NKRO_ENABLE = yes           # Enable N-Key Rollover
#RGB_MATRIX_ENABLE = yes
#OLED_ENABLE = yes
##OLED_DRIVER = SSD1306


WPM_ENABLE = yes
#EXTRAKEY_ENABLE = yes       # Audio control and System control
#
#ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes
#
#OPT_DEFS += -DHAL_USE_I2C=TRUE
