
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_INVERT_Y
#define ROTATIONAL_TRANSFORM_ANGLE  -25
#define POINTING_DEVICE_RIGHT
// #define POINTING_DEVICE_COMBINED
#define PMW33XX_CS_PIN GP21
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define PMW33XX_LIFTOFF_DISTANCE 0x03

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
// only required if not setting mouse layer elsewhere
#define AUTO_MOUSE_DEFAULT_LAYER 3

#define DYNAMIC_KEYMAP_LAYER_COUNT 5


/* ADNS 9800 SETTINGS */

// #define ADNS9800_CS_PIN GP21
// #define POINTING_DEVICE_DEBUG
// #define ADNS9800_CPI 8200

// #define POINTING_DEVICE_INVERT_Y
// #define POINTING_DEVICE_INVERT_Y_RIGHT   // FOR DUAL