// Dactyl Manuform Hotswap
#pragma once

//#include QMK_KEYBOARD_H
// Basic Config

//#define PRODUCT_ID 0x0002

#define SPLIT_POINTING_ENABLE
//#define ROTATIONAL_TRANSFORM_ANGLE  -25
#define PMW33XX_CS_PIN GP21
//#define POINTING_DEVICE_CS_PIN GP21

#define SPLIT_TRANSACTION_IDS_KB RPC_ID_KB_CONFIG_SYNC

#define CHARYBDIS_MINIMUM_DEFAULT_DPI 600
//#define CHARYBDIS_MAX_DEFAULT_DPI_MULTIPLIER 0x08
//#define CHARYBDIS_BASE_DEFAULT_DPI_MULTIPLIER 0x02
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 400
#define CHARYBDIS_MINIMUM_SNIPING_DPI 400
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 200
#define CHARYBDIS_DRAGSCROLL_DPI 200
#define CHARYBDIS_POINTER_ACCELERATION_ENABLE

// End of Basic Config
